### ISSUE TITLE
Picture load failed after last update(0.3.12)

### ISSUE THREAD

**Issue by lzlzlizi** [shd101wyy/markdown-preview-enhanced#1080]
```![some Picture](picture_file_name.jpg)``` doesn't working on my computer now, win10 & ubuntu18.04 vscode1.32.1

**Comment by shd101wyy** [comment]
That's weird. 
Did you open the folder first then open that markdown file? Because now vscode has restrictions to access files for security reasons https://github.com/shd101wyy/vscode-markdown-preview-enhanced/blob/dccb36e226e56a3f13bbec27da3c8667b697dbe8/src/preview-content-provider.ts#L335.
Thanks!

**Comment by lzlzlizi** [comment]
It works. Thanks. I think I should make a habit to open the folder first form now.
