### ISSUE TITLE
Output plain-text code block insufficient contrast

### ISSUE THREAD

**Issue by stiflervn** [shd101wyy/markdown-preview-enhanced#159]
The output for the plain-text code block does not have sufficient contrast. For example, the code below for `php.ini` 
\`\`\`
max_execution_time=600
post_max_size=128M
upload_max_filesize=128M
\`\`\`
is rendered in HTML, PDF as:
![Imgur](http://i.imgur.com/VRfZTub.png)

The current value is `#CDD3DE`. Maybe change it to `#666` or  `#333`

**Comment by shd101wyy** [comment]
Hi @stiflervn ,

I just tried the code snippet you pasted. But I didn't get the issue that you mentioned.  
<img width="1178" alt="screen shot 2016-10-13 at 1 57 11 pm" src="https://cloud.githubusercontent.com/assets/1908863/19362643/137a3ee0-914d-11e6-8c5a-a8e2d1bba4b3.png">

Are you using `Github.com style` ?  
<img width="418" alt="screen shot 2016-10-13 at 1 57 17 pm" src="https://cloud.githubusercontent.com/assets/1908863/19362654/1d52fd94-914d-11e6-9551-b3f8f88cff5a.png">  

I think this issue might be caused by package conflict. Try disabling other markdown packages to see if this issue still happens.  

Thanks

**Comment by stiflervn** [comment]
Hey @shd101wyy ,
Thanks for the speedy reply. You're right. It's because of the theme syntax. I was using Material UI theme & syntax. I switched back to the One Dark theme + syntax and it's fine now.
