### ISSUE TITLE
support for gitgraph in mermaid

### ISSUE THREAD

**Issue by k-byun** [shd101wyy/markdown-preview-enhanced#1697]
Does the `markdown-preview-enhanced` currently support `gitGraph` as shown: 
https://mermaid-js.github.io/mermaid/#/

Within atom, I had:
![image](https://user-images.githubusercontent.com/72177353/166006273-e66a2068-93c9-4ce5-8131-a9a9c8d530fe.png)

but it generates:
![image](https://user-images.githubusercontent.com/72177353/166005499-7fb1268d-a8e6-4616-9f3a-1232e7a1b981.png)

Referring to other issue reporting, I had gone into the following folder, but I can't seem to figure out why `markdown-preview-enhanced` is not rendering the graph:
`%userprofile%\.atom\packages\markdown-preview-enhanced\node_modules\@shd101wyy\mume\dependencies\mermaid`

**Comment by k-byun** [comment]
any help would greatly be appreciated.

**Comment by k-byun** [comment]
Can anyone point me into the right direction in resolving this?  Any docs or discussion that will lead me fix this issue?

**Comment by adichou** [comment]
the root cause is the mermaid version used by MPE is older , not support gitGraph. I just downloaded the mermaid.min.js of 9.4.0 version in https://cdn.jsdelivr.net/npm/mermaid@9.4.0/dist/, to replace the same file in my windows. C:\Users\{yourname}\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.6.2\node_modules\@shd101wyy\mume\dependencies\mermaid. and it works.

**Comment by shd101wyy** [comment]
It should be working now. I have updated mermaid to the latest version.
