### ISSUE TITLE
Feature request: allowing choosing Katex or MathJax on a per-block basis

### ISSUE THREAD

**Issue by guoshimin** [shd101wyy/markdown-preview-enhanced#278]
Katex is faster so I want to use Katex when it suffices, but MathJax has more features so sometimes I have to use MathJax. It would be nice if I can use MathJax only for places where it's necessary.

**Comment by shd101wyy** [comment]
Hi @guoshimin ,

I would like to recommend you to stick with MathJax.  
I feel the performance is not a big issue. Because for this markdown preview package, the math rendered already will not be rendered again. A math block will only be rerendered when it gets changed or a new math block is inserted before it.  

Thanks.

**Comment by guoshimin** [comment]
@shd101wyy Thanks for the suggestion. Yes I tried MathJax and the rendering speed was very reasonable. Closing this issue.
