### ISSUE TITLE
REQUEST: Render matplotlib figures in preview window

### ISSUE THREAD

**Issue by sonichopsticks** [shd101wyy/markdown-preview-enhanced#280]
It would be greatly appreciated if support for the preview pane to be able to render matplotlib figures without having to first save the image. Something similar to what the Hydrogen packages does within in your source code, but in the preview pane.

**Comment by shd101wyy** [comment]
Hi @sonichopsticks ,  
What I did is like this  
<pre>
```{python output:"html", id:"iz9fkgdk"}
import matplotlib.pyplot as plt
import StringIO
from matplotlib import numpy as np

x = np.arange(0,np.pi*3,.1)
y = np.sin(x)

fig = plt.figure()
plt.plot(x,y)

# get svg data
imgdata = StringIO.StringIO()
fig.savefig(imgdata, format='svg')
imgdata.seek(0)  # rewind the data
svg_dta = imgdata.buf  # this is svg data

print(svg_dta)
```
</pre>

So I print `svg_dta` in the end. And set code chunk `output:'html'`      

Thanks

**Comment by shd101wyy** [comment]
Hydrogen is very cool!

**Comment by sonichopsticks** [comment]
Works like a charm! Thank you so much! I would suggest including your response in the code chunk (beta) section of the documentation:

https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/code-chunk.md#demo

Thanks again!

**Comment by shd101wyy** [comment]
I haven't used Juypter or IPython notebook for a long time.    
(Last time was 2 years ago when I was taking numerical analysis class haha, bad memory).  
If I remember correctly, you have to write something at the most front of your python code to tell the notebook that you want something embeded.  
Like `%matplotlib inline`.    

So my plan is that if you write code chunk like this:   

 <pre>
```{python output:"html", id:"iz9fkgdk"}
%matplotlib inline
import matplotlib.pyplot as plt
import StringIO
from matplotlib import numpy as np

x = np.arange(0,np.pi*3,.1)
y = np.sin(x)

fig = plt.figure()
plt.plot(x,y)
```
</pre>

Then I automatically append  
<pre>
# get svg data
imgdata = StringIO.StringIO()
fig.savefig(imgdata, format='svg')
imgdata.seek(0)  # rewind the data
svg_dta = imgdata.buf  # this is svg data

print(svg_dta)
</pre>

for you so that you don't need to set it by yourself?

**Comment by shd101wyy** [comment]
@sonichopsticks , you can now use `matplotlib:true` option.     

Here is a [demo](https://cdn.rawgit.com/shd101wyy/markdown-preview-enhanced/f83acb43/test/code-chunks-test.html#mpld3-interactive-graphs)

**Comment by sonichopsticks** [comment]
This is awesome and exactly what I was looking for!

Thanks again!

**Comment by shd101wyy** [comment]
closing this issue
