### ISSUE TITLE
Issue with application linking

### ISSUE THREAD

**Issue by danielmj** [shd101wyy/markdown-preview-enhanced#288]
Application links do not work on the Mac . There are a handful of applications that I would love to link against, but can't. They are being mislabeled as file references. An example of the issue is illustrated below:

```
In Markdown:
[Test iTunes Link](itms://itunes.apple.com/us/app/apple-store/id375380948?mt=8)
```

This, however, the markdown preview currently translates this to the following link:

```
<a href="file:////Users/dan/Notes/Agendas/itms:/itunes.apple.com/us/app/apple-store/id375380948?mt=8">Test iTunes Link</a>
```

And should be:

```
<a href="itms://itunes.apple.com/us/app/apple-store/id375380948?mt=8">Test iTunes Link</a>
```

**Comment by shd101wyy** [comment]
Hi @danielmj ,

Ok I see. Is there any other protocols that you want me to support except `itms://`

Thanks

**Comment by danielmj** [comment]
Since any application can specify a protocol by which that application will respond to, the options are infinite. It would be awesome if it could just take any text preceding a `://` as a valid protocol. Or possibly have an area to whitelist protocols that are used. t

A list of ones I use the top of my head would be:

itms://
facetime://
tel://
mailto:
omnifocus://
rdar://

**Comment by shd101wyy** [comment]
Hi @danielmj ,

Done. You can now set protocols whitelist:   
![screen shot 2017-02-21 at 6 16 43 pm](https://cloud.githubusercontent.com/assets/1908863/23191200/f82bcfe2-f861-11e6-90c6-9a64cdeaec76.png)  
Restarting atom is required to take effect.  
I didn't use the first approach that you mentioned because it will slow down the performance, so I used the second approach.  

Cheers.

**Comment by danielmj** [comment]
That works perfect! Thank you very much!
