### ISSUE TITLE
Shortcuts for other non-UML languages with PlantUML

### ISSUE THREAD

**Issue by roipoussiere** [shd101wyy/markdown-preview-enhanced#318]
PlantUML allows non-UML diagrams, such as [salt and dot](http://plantuml.com/salt) syntax.

This one is correctly supported using this syntax:

````
```puml
salt
{
  [This is my button]
  [X] Checked box
}
```
````

A nice shortcut should be to call salt (and maybe ditaa in the future) using `salt` , `dot` and `ditaa` as language keywords; for instance:

````
```salt
{
  [This is my button]
  [X] Checked box
}
```
````

**Comment by shd101wyy** [comment]
I think it would be very hard to support such shortcuts because it's hard for me to know whether that graph is a plantuml graph or not. For example, given `salt`, I need to hardcode it as plantuml. 
So I would suggest you to stick to the first method, which is more clear.

**Comment by roipoussiere** [comment]
I though that it was not so difficult, for me you just need to add `salt` to the list of PlantUML keywords (which is currently `puml`, `plantuml`, `@puml` and `@plantuml`), then if the keyword is `salt`, you add `salt` before the text before the conversion.

**Comment by shd101wyy** [comment]
I mean I feel this is unnecessary since `plantuml` just works fine.  
Since `salt` is a part of `plantuml`, I still suggest you to write it inside <code>\`\`\`plantuml</code>.   
What would happen if there appears more keywords like `salt` in the future, adding them one by one would not be easy.   
Thanks :)
