### ISSUE TITLE
Feature Request: manual "sync here" command

### ISSUE THREAD

**Issue by lewallen** [shd101wyy/markdown-preview-enhanced#424]
I was wondering if there could be an optional "sync here" command added, which when triggered at a certain location in the split-pane preview (via right-click, say), would sync the source window to that location (this is how sync is implemented in markdown-preview-plus, for example) (And vice-versa as well, if that's technically feasible). Personally, I much prefer this to the constant-sync feature which is currently available.

Of course if this is already an option, please let me know.

And thanks for the great package!!

**Comment by shd101wyy** [comment]
Hello,

I don't think that I will implement the "sync window" like you mentioned because I think it is unnecessary. 

Thanks

**Comment by shd101wyy** [comment]
I think automatic scroll sync is so much better than the manual scroll sync.

**Comment by lewallen** [comment]
Well, I personally can't use the automatic scroll option, because 1) it is too visually distracting and 2) it doesn't allow to move the preview independently, which is often desirable (e.g. one is editing the source, and wants to look somewhere else in the preview without changing the source location; for me that is actually my most common scenario for using the preview). Maybe it's fair to say that the manual and automatic options aren't really comparable, they suit complementary use-cases. 

I presume there must be others that share my preference, but if you don't want to implement it, no problem! Maybe at some point I'll try to take a look at importing the code form mpp if I get the time.

Thanks!

**Comment by shd101wyy** [comment]
Ok I see. I will try to support it in next release, but not guaranteed though :)

**Comment by shd101wyy** [comment]
Hi,@lewallen ,

You can now use `Markdown Preview Enhanced: Sync Preview` and `Markdown Preview Enhanced: Sync Source` commands. Or right click at the markdown or preview window.  
The keyboard shortcut right now is `ctrl-shift-S`.  Tell me if you have any other good keyboard shortcut options.  
However, it doesn't work the same as the `markdown-preview-plus` package because we use two different markdown parsers. So this package will only sync the document to an approximately close location and it's less accurate.  

Thanks

**Comment by lewallen** [comment]
Hi @shd101wyy ,

sorry for such a delayed reply, and thanks a lot for such a quick response and including the feature! I hope it will benefit others as well :) Again, very great package

-sam
