### ISSUE TITLE
Markdown Emojis from autocomplete-emojis don't display 

### ISSUE THREAD

**Issue by message2prateek** [shd101wyy/markdown-preview-enhanced#512]
Version/Platform Information
-------------------------------
1.  Atom 1.18.0 is32
2.  OS Windows 8 X64
3. Markdown preview enhanced 0.14.2
4. Autocomplete-emojis plugin version 2.5.0

Steps to reproduce the problem
------------------------------------
1. Create a new markdown file
2. Choose to add an emoji to the file using the autocomplete-emojis plugin.
![image](https://user-images.githubusercontent.com/18386256/28349598-f1586c98-6c97-11e7-8c72-9f00af8fbd3b.png)

Expected Output
------------------
User can add both Unicode and Markdown flavor emojis to the file

Actual Output
---------------
1. User can add Unicode emojis successfully
![image](https://user-images.githubusercontent.com/18386256/28349720-a6d1f238-6c98-11e7-8dcd-577e50acc84e.png)

2. User is NOT able to add Markdown emojis
![image](https://user-images.githubusercontent.com/18386256/28349751-cc5b93c4-6c98-11e7-8e4a-b91ec7649b1a.png)

![image](https://user-images.githubusercontent.com/18386256/28349766-e21aef3e-6c98-11e7-8e12-8b359b012285.png)

**Comment by shd101wyy** [comment]
Set `Enable Unicode Emojis` under `autocomplete-emojis` package to be true, then insert emoji directly to your markdown file.

![screen shot 2017-07-22 at 4 04 48 am](https://user-images.githubusercontent.com/1908863/28489876-ed45784c-6e92-11e7-9e8f-9c37fa23f798.png)

**Comment by message2prateek** [comment]
I have the settings enabled, but still, the emojis don't show up for me. Please guide.

![image](https://user-images.githubusercontent.com/18386256/28495101-8a55aab2-6f97-11e7-812d-e5afdad55d4f.png)

**Comment by shd101wyy** [comment]
I don't really know why it doesn't work on your computer.  
I also just tried on my Windows 10 machine and it works perfectly.  
So I think your system has to have builtin emoji support in order to use `autocomplete-emojis`.  
From your screenshot, I assume that you are not using `Windows 10`?  


![capture](https://user-images.githubusercontent.com/1908863/28495227-94661a18-6f0c-11e7-98e3-80f8fa054d19.PNG)
![capture2](https://user-images.githubusercontent.com/1908863/28495228-957ff27a-6f0c-11e7-8fc6-1814010852e9.PNG)

**Comment by shd101wyy** [comment]
[How To Use Emojis On Windows 8 and Windows 8.1](http://blog.getemoji.com/post/125170927430/how-to-use-emojis-on-windows-8-and-windows-81)

**Comment by message2prateek** [comment]
Thanks for the link. Seems like a problem with system.

**Comment by Maxiride** [comment]
Reopening this issue since I'm having the same issue.

Emojis are not showing, writing ::apple or :apple: does open the `autocomplete-emojis` dropdown but on the preview there is the plain text of the emoji.

I can confirm that with the built-in atom preview emojis are shown properly. I've tried both markdown and unicode ones without succes.

**Comment by shd101wyy** [comment]
@Maxiride @message2prateek I will add emoji and fontawesome support in next release. Thanks.

**Comment by shd101wyy** [comment]
@message2prateek @Maxiride Both emoji and font-awesome are supported now.  

You can disable it from the package settings.   
![screen shot 2017-09-30 at 9 32 11 pm](https://user-images.githubusercontent.com/1908863/31051176-d87e648e-a626-11e7-8e50-694bee25ff70.png)

Cheers :)

**Comment by Maxiride** [comment]
Thank you very much for the time dedicated to this improvement :) well done!

**Comment by message2prateek** [comment]
Thanks a lot for your hard work 👍 Really appreciate it.
