### ISSUE TITLE
PDF export removed?

### ISSUE THREAD

**Issue by MBuchalik** [shd101wyy/markdown-preview-enhanced#522]
Hi,

first of all - I really like your plugin. :smiley:

I have a probably pretty stupid question but could not find an answer to this. I have used version 0.13.0 before and here I could press the "export to disk" button. After this, there was an option "PDF" where I could set the margin, format, orientation etc.
In version 0.14.3, I cannot see an option like this on Windows 10. Has the original method for PDF exports been removed or can I still find it somewhere else? (Or is there any "hack" I can use to export PDFs in the same way as before? I loved this easy option :smile:)

**Comment by shd101wyy** [comment]
Hi @MBuchalik ,

Yes, it was removed after version `0.14.0`. I removed it because it didn't work well as sometimes the math or diagrams will not be rendered correctly.  
The alternative way to achieve the same effect as the old `PDF export` is to right click at the preview, then choose `Open in Browser`, and after that print the webpage as PDF from the browser.  
Please check [this doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/pdf).  
Also, you could try `PhantomJS` and `Prince` PDF export.  

Thanks

**Comment by MBuchalik** [comment]
@shd101wyy Thanks for your reply! I already tried PhantomJS but in my case the result didn't look as good as I hoped it would. 
The PDF creation after using the ```Open in Browser``` function seems to work fine :smiley: It adds a few steps when trying to finish a document but I think that shouldn't take too much additional time.

Thank you!
