### ISSUE TITLE
Is possible to add a options for never show welcome again?

### ISSUE THREAD

**Issue by Cologler** [shd101wyy/markdown-preview-enhanced#568]
Is possible to add a options for never show welcome again?

**Comment by shd101wyy** [comment]
It will show once every time you upgrade this package.

**Comment by Cologler** [comment]
Why it can not quiet upgrade?

**Comment by shd101wyy** [comment]
Just in order to show the changes and updates. I will reduce the frequency
of updating this package.

I might add an option to disable it in the future.

I think I will be absent for like a month. So you won't see welcome page
again within a month :)

**Comment by jacobmischka** [comment]
I would very much like this. I feel like every time I open a markdown file I'm greeted with a bunch of html, I'm likely to uninstall this package without a way to disable it, which is unfortunate because it's otherwise very good.

Please reconsider, but regardless thank you for your work on this package.

**Comment by shd101wyy** [comment]
Ok. I decide to forever disable the welcome page. 

You will not see that again in next release.

Thanks

**Comment by jacobmischka** [comment]
Thank you!

**Comment by shd101wyy** [comment]
@Cologler @jacobmischka Done.
