### ISSUE TITLE
Changes to embedded TOC

### ISSUE THREAD

**Issue by werunom** [shd101wyy/markdown-preview-enhanced#583]
Can you please include the following two important options/changes in the embedded TOC - 
1. An option not to have the toc-entries as hyperlinks
2. And the orderedlist list can have actual ordered numbers (as against the "1." that is appended"

Let me illustrate what I want through an example. At present, the embedded toc in the markdown file looks like below

```
<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=true} -->
<!-- code_chunk_output -->

1. [Header 1](#header-1)
    1. [Header 1-a](#header-1-a)
1. [Hearder 2](#hearder-2)
    1. [Header 2-a](#header-2-a)
    1. [Header 2-b](#header-2-b)
    1. [Header 2-c](#header-2-c)
1. [Header 3](#header-3)
    1. [Header 3-a](#header-3-a)
    1. [Header 3-b](#header-3-b)

<!-- /code_chunk_output -->
```
And what I am requesting for is something like this 
```
<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=true} -->
<!-- code_chunk_output -->

1. Header 1
    1. Header 1-a
2. Header 2
    1. Header 2-a
    2. Header 2-b
    3. Header 2-c
3. Header 3
    1. Header 3-a
    2. Header 3-b

<!-- /code_chunk_output -->
```
With this, the embedded TOC looks more readable and intuitive. 

Note that - what I am requesting for is very similar to how the TOC looks when the preview has been generated. 

Thanks!

**Comment by ttasovac** [comment]
There are two issues here: the fact that ordered lists do not render their numbers properly in the Markdown ToC (although they do in Preview); and the formatting of ToC links in Markdown. 

Your first request makes sense, because it's a bug. But you are also asking for Markdown links to be hidden in ToC, i.e. you want @shd101wyy's package to ignore Markdown syntax.  I don't think that would be a good thing. Plus, as you said yourself, the links are nicely formatted and rendered in the preview, as they should be. 

Just my 2 cents.

**Comment by shd101wyy** [comment]
@werunom Done. You can set `ignoreLink=true`.

**Comment by werunom** [comment]
@shd101wyy - brilliant! Thanks for this. I also see that orderedlist is working fine :) 👍 

@ttasovac - I thought that was possible because I used the package [markdown-toc](https://atom.io/packages/markdown-toc) before, where there is an option of enabling/disabling the link.
Apart from the possibility, the need for this arises because not all work with rendered markdowns (in  html/pdf formats). I work with raw markdown for my thesis note taking and because of that I would need readability here itself :)
