### ISSUE TITLE
Support full width by default for [Open in Brower] / [Export to HTML]

### ISSUE THREAD

**Issue by herohuyongtao** [shd101wyy/markdown-preview-enhanced#69]
It will help a lot if it supports **full width** by default for _`[Open in Brower]`_ / _`[Export to HTML]`_. Currently, it will show the content at fixed width (will break too many lines for long texts) even for wider screens.

**Comment by shd101wyy** [comment]
Hi @herohuyongtao ,

You can change it to **full width** by running **Markdown Preview Enhanced: Customize CSS** command.

Then edit  **.markdown-preview-enhanced-custom** in **style.less** like this:
![gg](https://ooo.0o0.ooo/2016/07/07/577e433faa6a5.png)

Thanks.

**Comment by herohuyongtao** [comment]
Thanks for the quick hint fix. :+1:

**Comment by ChrisHastieIW** [comment]
Hi, 

I'm trying to enable full width for html and it doesn't seem to be working. I've followed the above, and this is my .markdown-preview-enhanced-custom modification in style.less:

![2020-03-04_14h16_23](https://user-images.githubusercontent.com/47250945/75888095-be21b300-5e22-11ea-9562-63208391768b.png)

The problem is, when I view any of the html documents they still do not span the full width. Any advice please?

Cheers,
Chris
