### ISSUE TITLE
Feature request: Open previewer in top bottom split

### ISSUE THREAD

**Issue by 2E0PGS** [shd101wyy/markdown-preview-enhanced#747]
Hi great package its the best for markdown I have found!

Anyway I have a feature request. Add option to allow preview to open in a split screen top is md and the bottom is the preview. Instead of current: left is md and right is preview.

So this would be like split down instead of split right. I did try manually moving that preview window down but it caused issues.

**Comment by shd101wyy** [comment]
Will do. Thanks. 
But if I recall correctly, I tried splitting pane on the right side but it didn't work very well.
I will try this time.

**Comment by 2E0PGS** [comment]
So currently we have this style:
![image](https://user-images.githubusercontent.com/15659301/34663205-923b4d8c-f44d-11e7-8889-4cda25073f3c.png)

But I would like an option to do this style:
![image](https://user-images.githubusercontent.com/15659301/34663211-a1c3c798-f44d-11e7-98b5-8e71d393287f.png)

**Comment by shd101wyy** [comment]
![screenshot from 2018-01-08 21-03-38](https://user-images.githubusercontent.com/1908863/34703217-70a49222-f4b7-11e7-9f82-2f8218951b23.png)

Done, check `Position of the preview pane`

Thanks

**Comment by 2E0PGS** [comment]
Awesome thanks! 

Wouldn't it be better to have "Top", "Bottom", "Left", "Right". Instead of "up" and presumably "down" etc. 

I am not too worried myself since you now added the functionality I wanted but from an English language perspective top and bottom would make more sense than up or down.

**Comment by shd101wyy** [comment]
Hmm I just copied the terms used in atom.workspace.open function API. Maybe
I will change it in the future. Thanks

On Jan 9, 2018 2:49 AM, "Peter Stevenson" <notifications@github.com> wrote:

Awesome thanks!

Wouldn't it be better to have "Top", "Bottom", "Left", "Right". Instead of
"up" and presumably "down" etc.

I am not too worried myself since you now added the functionality I wanted
but from an English language perspective top and bottom would make more
sense than up or down.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/shd101wyy/markdown-preview-enhanced/issues/747#issuecomment-356218689>,
or mute the thread

**Comment by 2E0PGS** [comment]
I see. That's odd because atom uses the terms I mention in their UI for splitting regular panes. I guess its their consistency issue.

Also when is the next version going to be published for install via atom.

**Comment by shd101wyy** [comment]
The version 0.15.2 was just published tonight a few hours ago. I don't have
a plan for the next version now.

**Comment by 2E0PGS** [comment]
Ok thanks! I will give it an update and try!

**Comment by 2E0PGS** [comment]
Works like a charm thanks! I will close this issue now.
