### ISSUE TITLE
Theme for HTML export

### ISSUE THREAD

**Issue by sheljohn** [shd101wyy/markdown-preview-enhanced#782]
I am using the extension with VSCode:
```
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

I cannot seem to find instructions anywhere to change the theme of the HTML export?
My user settings at the moment are:
```
"markdown-preview-enhanced.liveUpdate": false,
"markdown-preview-enhanced.previewTheme": "github-dark.css",
"markdown-preview-enhanced.printBackground": false,
"markdown-preview-enhanced.frontMatterRenderingOption": "none",
"markdown-preview-enhanced.revealjsTheme": "serif.css",
"markdown-preview-enhanced.mermaidTheme": "mermaid.dark.css"
```

Looking at the HTML output `<style>` section, it seems that the default theme is a combination of 
 [`prism.js` Github theme](https://github.com/shd101wyy/mume/blob/master/styles/prism_theme/github.css) and the preview theme [github-light](https://github.com/shd101wyy/mume/blob/master/styles/preview_theme/github-light.css). Is it possible to customise these?

**Comment by sheljohn** [comment]
My bad, [apparently using the preview theme depends on the option `print_background`](https://github.com/shd101wyy/mume/blob/2850adcce8f91f70646267dd615e2ec028499533/src/markdown-engine.ts#L920-L927) to be put in the YAML configuration at the very top of the file:

```
---
print_background: true
---
```

**Comment by WetABQ** [comment]
Just a note

If you could not correctly render the content of your document (usually because of large content), you could try the following front-matter of Puppeteer.

```
---
puppeteer:
  timeout: 3000
---
```

You could use `Open Browser`, then you may find that the content will need a short period of time to load, so we need to set a waiting time for Puppeteer.

Also see: [https://github.com/puppeteer/puppeteer/issues/4647](https://github.com/puppeteer/puppeteer/issues/4647)
